Task154
FacturaScripts/backup pull request #6
Opened 2024-10-16 13:54 UTC by SYK360

# Descripción
- Se implementó el proceso de copia de seguridad en dos pasos, almacenando el respaldo en la carpeta MyFiles/Backup.
- Se sobrescribió la clase SimpleBackup para optimizar la exportación del archivo .sql y evitar carga innecesaria en memoria.
- Se implementó un aviso para respaldos con más de 30 días de antigüedad.

## ¿Cómo has probado los cambios?
Toda modificación debe haber sido mínimamente probada. Marca o describe las pruebas que has realizado:
- [x] He revisado mi código antes de enviarlo.
- [x] He probado que funciona correctamente en mi PC.
- [x] He probado que funciona correctamente con una base de datos vacía.
- [ ] He ejecutado los tests unitarios.

2025-01-08 11:57 UTC, NeoRazorX requested changes

2025-01-08 11:57 UTC, NeoRazorX commented on Extension/Controller/ListFacturaCliente.php
> +                return false;
Al estar la caché vacía, el resto del código nunca se ejecutará

2025-01-08 11:57 UTC, NeoRazorX commented on Extension/Controller/ListFacturaCliente.php
> +    public function createViews()
Falta : Closure

No es fundamental, pero si una buena práctica.

2025-01-08 11:57 UTC, NeoRazorX commented on Extension/Controller/ListFacturaCliente.php
> +    public function checkDateLastBackupDB(){
Falta : Closure

No es fundamental, pero si una buena práctica.

2025-01-08 11:57 UTC, NeoRazorX commented on Controller/Backup.php
> +        Cache::set('backup-db-last', $fileName);
Si el usuario tiene que entrar primero en el "menú administrador, backup", para que desde "ventas, facturas" le avise de que el backup es antiguo ... estos cambios no sirven de nada.

Lo que buscaba es que "ventas, facturas" hiciese la comprobación él solo. Al fin y al cabo, los backups estarán almacenados en la carpeta MyFiles

2025-01-15 02:52 UTC, SYK360 commented on Controller/Backup.php
> +        Cache::set('backup-db-last', $fileName);
Veo que has implementado el proceso que mencionas en la rama master de este repositorio. Por favor, avísame si deseas que lo implemente de esta manera en este PR.

2025-01-15 12:24 UTC, NeoRazorX commented on Controller/Backup.php
> +        Cache::set('backup-db-last', $fileName);
No, al final me puse y lo reimplementé entero.

2025-01-15 12:24 UTC, closed without merging